#ifndef CODER_H
#define CODER_H

/*coder's pins*/
#define CODER_L_A    (4)
#define CODER_L_B    (3)
#define CODER_R_A    (5)
#define CODER_R_B    (6)

#define DEBUG_PIN_ASSERV 12
#define DEBUG_PIN_GENERAL 13

#define MOTOR_L_PWM		10
#define MOTOR_L_DIR		11
#define MOTOR_L_BRAKE	12
#define MOTOR_L_SENSE	A1

#define MOTOR_R_PWM		9
#define MOTOR_R_DIR		7
#define MOTOR_R_BRAKE	8
#define MOTOR_R_SENSE	A0

#define DEFAULT_TICK_PER_METERS (4798.0)
#define DEFAULT_TICK_PER_RADS (488.2159)

//refresh frequency of the PID and odometry, in Hz
#define REFRESH_FREQ 1000

//Absolute pwm that must not be exceded to avoid damaging the motors
#define PWM_MAX 255

//frequency off the pwm (the noise generated by the pwm become almost inaudible above 16khz)
#define PWM_FREQ 16000

//If the target pwm is < ZONE_51 it will be considered equal to 0
//Avoid useless "biiiiiiiiiii" from the motors when to pwm is to low to make it move
#define ZONE_51	0

#define ACK_DIST	0.02 //en m
#define ACK_ANGLE	0.02 //en rad

#define DIST_WHEEL2CENTER (0.055)

#define I2C_ADDR	0x42

#define SERVO_COUNT 4
#define SERVO_1_PIN 21
#define SERVO_2_PIN 21
#define SERVO_3_PIN 21
#define SERVO_4_PIN 21

#define SERVO_RATATOUILLE_1 1
#define SERVO_RATATOUILLE_1_ANGLE_IDLE 20
#define SERVO_RATATOUILLE_1_ANGLE_TOP 20
#define SERVO_RATATOUILLE_1_ANGLE_BOTTOM 20
#define SERVO_RATATOUILLE_2 2
#define SERVO_RATATOUILLE_2_ANGLE_IDLE 20
#define SERVO_RATATOUILLE_2_ANGLE_TOP 20
#define SERVO_RATATOUILLE_2_ANGLE_BOTTOM 20

#define SERVO_NET_RIGHT 3
#define SERVO_NET_RIGHT_ANGLE_IDLE 20
#define SERVO_NET_RIGHT_ANGLE_TRIGGER 20

#define SERVO_NET_LEFT 4
#define SERVO_NET_LEFT_ANGLE_IDLE 20
#define SERVO_NET_LEFT_ANGLE_TRIGGER 20

#endif
